server.port: 8080

spring.application.name: eureka-client

eureka:
  client:
    refresh.enable: false
    healthcheck.enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health.show-details: always
    info.access: read_only

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG